### ISSUE TITLE
text quality

### ISSUE THREAD

**Issue by meangrape** [bensteinberg/a-novel-factory#1]
I really think you should work on this with some AI-type thing.

**Comment by meangrape** [comment]
Or maybe mechanical turk. One paragraph per job.

**Comment by bensteinberg** [comment]
Mechanical turk is good -- a lorem Provider that is... a human writing prose. For that matter, you could harness the power of the humans doing NaNoWriMo.

**Comment by meangrape** [comment]
NaNoLoreMo
